apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
  namespace: {{ namespace }}
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  serviceName: "elasticsearch-discovery"
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm: 
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - elasticsearch
                - key: role
                  operator: In
                  values:
                  - master
              topologyKey: kubernetes.io/hostname
      nodeSelector:
        NodeType: {{ preferred_node }}
      containers:
      - name: es-master
        resources:
          limits:
            memory: 1024Mi
            cpu: "1.0"
          requests:
            memory: 512Mi
            cpu: "0.1"
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: lambdalab/elasticsearch-xpack:5.5.2
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms512m -Xmx512m"
        - name: "NETWORK_HOST"
          value: "0.0.0.0"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
